In [1]:
import pandas as pd
import numpy as np

In [7]:
df = pd.read_csv(r"C:\Users\ashis\OneDrive\Desktop\CDAC\Advanced Analytics\Advanced-Analytics\Classwork\titanic.csv")
df

     survived  pclass  gender   age  sibsp  parch     fare embarked deck
0           0       3    male  22.0      1      0   7.2500        S  NaN
1           1       1  female  38.0      1      0  71.2833        C    C
2           1       3  female  26.0      0      0   7.9250        S  NaN
3           1       1  female  35.0      1      0  53.1000        S    C
4           0       3    male  35.0      0      0   8.0500        S  NaN
..        ...     ...     ...   ...    ...    ...      ...      ...  ...
886         0       2    male  27.0      0      0  13.0000        S  NaN
887         1       1  female  19.0      0      0  30.0000        S    B
888         0       3  female   NaN      1      2  23.4500        S  NaN
889         1       1    male  26.0      0      0  30.0000        C    C
890         0       3    male  32.0      0      0   7.7500        Q  NaN

[891 rows x 9 columns]

In [8]:
df.head(5)

   survived  pclass  gender   age  sibsp  parch     fare embarked deck
0         0       3    male  22.0      1      0   7.2500        S  NaN
1         1       1  female  38.0      1      0  71.2833        C    C
2         1       3  female  26.0      0      0   7.9250        S  NaN
3         1       1  female  35.0      1      0  53.1000        S    C
4         0       3    male  35.0      0      0   8.0500        S  NaN

In [9]:
df.tail(5)

     survived  pclass  gender   age  sibsp  parch   fare embarked deck
886         0       2    male  27.0      0      0  13.00        S  NaN
887         1       1  female  19.0      0      0  30.00        S    B
888         0       3  female   NaN      1      2  23.45        S  NaN
889         1       1    male  26.0      0      0  30.00        C    C
890         0       3    male  32.0      0      0   7.75        Q  NaN

In [12]:
df.shape

(891, 9)

In [13]:
df.columns

Index(['survived', 'pclass', 'gender', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'deck'],
      dtype='str')

In [14]:
df.dtypes

survived      int64
pclass        int64
gender          str
age         float64
sibsp         int64
parch         int64
fare        float64
embarked        str
deck            str
dtype: object

In [16]:
print(df.describe())

         survived      pclass         age       sibsp       parch        fare
count  891.000000  891.000000  714.000000  891.000000  891.000000  891.000000
mean     0.383838    2.308642   29.699118    0.523008    0.381594   32.204208
std      0.486592    0.836071   14.526497    1.102743    0.806057   49.693429
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    2.000000   20.125000    0.000000    0.000000    7.910400
50%      0.000000    3.000000   28.000000    0.000000    0.000000   14.454200
75%      1.000000    3.000000   38.000000    1.000000    0.000000   31.000000
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.329200

In [17]:
df[df["age"]>30]

     survived  pclass  gender   age  sibsp  parch     fare embarked deck
1           1       1  female  38.0      1      0  71.2833        C    C
3           1       1  female  35.0      1      0  53.1000        S    C
4           0       3    male  35.0      0      0   8.0500        S  NaN
6           0       1    male  54.0      0      0  51.8625        S    E
11          1       1  female  58.0      0      0  26.5500        S    C
..        ...     ...     ...   ...    ...    ...      ...      ...  ...
873         0       3    male  47.0      0      0   9.0000        S  NaN
879         1       1  female  56.0      0      1  83.1583        C    C
881         0       3    male  33.0      0      0   7.8958        S  NaN
885         0       3  female  39.0      0      5  29.1250        Q  NaN
890         0       3    male  32.0      0      0   7.7500        Q  NaN

[305 rows x 9 columns]

In [20]:
df[df["gender"]=="female"].head()

   survived  pclass  gender   age  sibsp  parch     fare embarked deck
1         1       1  female  38.0      1      0  71.2833        C    C
2         1       3  female  26.0      0      0   7.9250        S  NaN
3         1       1  female  35.0      1      0  53.1000        S    C
8         1       3  female  27.0      0      2  11.1333        S  NaN
9         1       2  female  14.0      1      0  30.0708        C  NaN

In [21]:
df

     survived  pclass  gender   age  sibsp  parch     fare embarked deck
0           0       3    male  22.0      1      0   7.2500        S  NaN
1           1       1  female  38.0      1      0  71.2833        C    C
2           1       3  female  26.0      0      0   7.9250        S  NaN
3           1       1  female  35.0      1      0  53.1000        S    C
4           0       3    male  35.0      0      0   8.0500        S  NaN
..        ...     ...     ...   ...    ...    ...      ...      ...  ...
886         0       2    male  27.0      0      0  13.0000        S  NaN
887         1       1  female  19.0      0      0  30.0000        S    B
888         0       3  female   NaN      1      2  23.4500        S  NaN
889         1       1    male  26.0      0      0  30.0000        C    C
890         0       3    male  32.0      0      0   7.7500        Q  NaN

[891 rows x 9 columns]

In [23]:
df[df["survived"]==1].head()

   survived  pclass  gender   age  sibsp  parch     fare embarked deck
1         1       1  female  38.0      1      0  71.2833        C    C
2         1       3  female  26.0      0      0   7.9250        S  NaN
3         1       1  female  35.0      1      0  53.1000        S    C
8         1       3  female  27.0      0      2  11.1333        S  NaN
9         1       2  female  14.0      1      0  30.0708        C  NaN

In [24]:
df[df["pclass"]==1].head()

    survived  pclass  gender   age  sibsp  parch     fare embarked deck
1          1       1  female  38.0      1      0  71.2833        C    C
3          1       1  female  35.0      1      0  53.1000        S    C
6          0       1    male  54.0      0      0  51.8625        S    E
11         1       1  female  58.0      0      0  26.5500        S    C
23         1       1    male  28.0      0      0  35.5000        S    A

In [25]:
df[df["fare"]>100].head()

     survived  pclass  gender   age  sibsp  parch      fare embarked deck
27          0       1    male  19.0      3      2  263.0000        S    C
31          1       1  female   NaN      1      0  146.5208        C    B
88          1       1  female  23.0      3      2  263.0000        S    C
118         0       1    male  24.0      0      1  247.5208        C    B
195         1       1  female  58.0      0      0  146.5208        C    B

In [26]:
df.query("age>30").head()

    survived  pclass  gender   age  sibsp  parch     fare embarked deck
1          1       1  female  38.0      1      0  71.2833        C    C
3          1       1  female  35.0      1      0  53.1000        S    C
4          0       3    male  35.0      0      0   8.0500        S  NaN
6          0       1    male  54.0      0      0  51.8625        S    E
11         1       1  female  58.0      0      0  26.5500        S    C

In [29]:
df.query("fare > 50").head()

    survived  pclass  gender   age  sibsp  parch      fare embarked deck
1          1       1  female  38.0      1      0   71.2833        C    C
3          1       1  female  35.0      1      0   53.1000        S    C
6          0       1    male  54.0      0      0   51.8625        S    E
27         0       1    male  19.0      3      2  263.0000        S    C
31         1       1  female   NaN      1      0  146.5208        C    B

In [30]:
df[df["embarked"]=="S"]

     survived  pclass  gender   age  sibsp  parch     fare embarked deck
0           0       3    male  22.0      1      0   7.2500        S  NaN
2           1       3  female  26.0      0      0   7.9250        S  NaN
3           1       1  female  35.0      1      0  53.1000        S    C
4           0       3    male  35.0      0      0   8.0500        S  NaN
6           0       1    male  54.0      0      0  51.8625        S    E
..        ...     ...     ...   ...    ...    ...      ...      ...  ...
883         0       2    male  28.0      0      0  10.5000        S  NaN
884         0       3    male  25.0      0      0   7.0500        S  NaN
886         0       2    male  27.0      0      0  13.0000        S  NaN
887         1       1  female  19.0      0      0  30.0000        S    B
888         0       3  female   NaN      1      2  23.4500        S  NaN

[644 rows x 9 columns]

In [31]:
df["pclass"].unique()

array([3, 1, 2])

In [32]:
df["embarked"].unique()

<StringArray>
['S', 'C', 'Q', nan]
Length: 4, dtype: str

In [34]:
df["pclass"].value_counts()

pclass
3    491
1    216
2    184
Name: count, dtype: int64

In [35]:
df["gender"].value_counts()

gender
male      577
female    314
Name: count, dtype: int64

In [36]:
df["survived"].value_counts()

survived
0    549
1    342
Name: count, dtype: int64

In [41]:
df.sort_values("fare",ascending=False).head(10)

     survived  pclass  gender   age  sibsp  parch      fare embarked deck
679         1       1    male  36.0      0      1  512.3292        C    B
258         1       1  female  35.0      0      0  512.3292        C  NaN
737         1       1    male  35.0      0      0  512.3292        C    B
88          1       1  female  23.0      3      2  263.0000        S    C
438         0       1    male  64.0      1      4  263.0000        S    C
341         1       1  female  24.0      3      2  263.0000        S    C
27          0       1    male  19.0      3      2  263.0000        S    C
742         1       1  female  21.0      2      2  262.3750        C    B
311         1       1  female  18.0      2      2  262.3750        C    B
299         1       1  female  50.0      0      1  247.5208        C    B

In [42]:
df.sort_values("age").head(10)

     survived  pclass  gender   age  sibsp  parch      fare embarked deck
803         1       3    male  0.42      0      1    8.5167        C  NaN
755         1       2    male  0.67      1      1   14.5000        S  NaN
644         1       3  female  0.75      2      1   19.2583        C  NaN
469         1       3  female  0.75      2      1   19.2583        C  NaN
78          1       2    male  0.83      0      2   29.0000        S  NaN
831         1       2    male  0.83      1      1   18.7500        S  NaN
305         1       1    male  0.92      1      2  151.5500        S    C
386         0       3    male  1.00      5      2   46.9000        S  NaN
172         1       3  female  1.00      1      1   11.1333        S  NaN
183         1       2    male  1.00      2      1   39.0000        S    F

In [43]:
df.sort_values("pclass")

     survived  pclass  gender   age  sibsp  parch     fare embarked deck
857         1       1    male  51.0      0      0  26.5500        S    E
862         1       1  female  48.0      0      0  25.9292        S    D
867         0       1    male  31.0      0      0  50.4958        S    A
52          1       1  female  49.0      1      0  76.7292        C    D
839         1       1    male   NaN      0      0  29.7000        C    C
..        ...     ...     ...   ...    ...    ...      ...      ...  ...
4           0       3    male  35.0      0      0   8.0500        S  NaN
888         0       3  female   NaN      1      2  23.4500        S  NaN
2           1       3  female  26.0      0      0   7.9250        S  NaN
890         0       3    male  32.0      0      0   7.7500        Q  NaN
0           0       3    male  22.0      1      0   7.2500        S  NaN

[891 rows x 9 columns]

In [45]:
df.sort_values("age")

     survived  pclass  gender   age  sibsp  parch     fare embarked deck
803         1       3    male  0.42      0      1   8.5167        C  NaN
755         1       2    male  0.67      1      1  14.5000        S  NaN
644         1       3  female  0.75      2      1  19.2583        C  NaN
469         1       3  female  0.75      2      1  19.2583        C  NaN
78          1       2    male  0.83      0      2  29.0000        S  NaN
..        ...     ...     ...   ...    ...    ...      ...      ...  ...
859         0       3    male   NaN      0      0   7.2292        C  NaN
863         0       3  female   NaN      8      2  69.5500        S  NaN
868         0       3    male   NaN      0      0   9.5000        S  NaN
878         0       3    male   NaN      0      0   7.8958        S  NaN
888         0       3  female   NaN      1      2  23.4500        S  NaN

[891 rows x 9 columns]

In [46]:
df.isnull().sum()

survived      0
pclass        0
gender        0
age         177
sibsp         0
parch         0
fare          0
embarked      2
deck        688
dtype: int64

In [47]:
df["age"].isnull().sum()

np.int64(177)

In [52]:
df["age"] = df["age"].fillna(0)
#df["age"].isnull().sum()

In [54]:
df=df.dropna()
df

     survived  pclass  gender   age  sibsp  parch     fare embarked deck
1           1       1  female  38.0      1      0  71.2833        C    C
3           1       1  female  35.0      1      0  53.1000        S    C
6           0       1    male  54.0      0      0  51.8625        S    E
10          1       3  female   4.0      1      1  16.7000        S    G
11          1       1  female  58.0      0      0  26.5500        S    C
..        ...     ...     ...   ...    ...    ...      ...      ...  ...
871         1       1  female  47.0      1      1  52.5542        S    D
872         0       1    male  33.0      0      0   5.0000        S    B
879         1       1  female  56.0      0      1  83.1583        C    C
887         1       1  female  19.0      0      0  30.0000        S    B
889         1       1    male  26.0      0      0  30.0000        C    C

[201 rows x 9 columns]

In [55]:
df["age"].mean()

np.float64(32.25582089552239)

In [60]:
df["embarked"].nunique()

3

In [79]:
survival_rate = df.groupby("pclass")["survived"].mean()

print(survival_rate)

highest_class = survival_rate.idxmax()
highest_rate = survival_rate.max()

print(f"Passenger class {highest_class} had the highest survival rate: {highest_rate:.2f}")

pclass
1    0.66474
2    0.81250
3    0.50000
Name: survived, dtype: float64
Passenger class 2 had the highest survival rate: 0.81

In [80]:
survival_rate = df.groupby("gender")["survived"].mean()

print(survival_rate)

highest_gender = survival_rate.idxmax()
highest_rate = survival_rate.max()

print(f"gender {highest_gender} had the highest survival rate: {highest_rate:.2f}")

gender
female    0.936842
male      0.424528
Name: survived, dtype: float64
gender female had the highest survival rate: 0.94

In [81]:
survival_rate = df.groupby("embarked")["pclass"].mean()

print(survival_rate)

highest_gender = survival_rate.idxmax()
highest_rate = survival_rate.max()

embarked
C    1.057971
Q    1.750000
S    1.257812
Name: pclass, dtype: float64